apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containerConcurrency: 80
      serviceAccountName: ${SERVICE_ACCOUNT_EMAIL}
      containers:
        - image: ${IMAGE}
          env:
            - name: OUTPUT_BUCKET_NAME
              value: ${OUTPUT_BUCKET_NAME}
  traffic:
    - percent: 100
      latestRevision: true
